window.DEFAULT_HERO_POOL = [
    'N-无漾', 'N-安娜', 'N-巴蒂斯特', 'N-布丽吉塔', 'N-禅雅塔', 'N-卢西奥', 'N-生命之梭', 'N-天使', 'N-雾子', 'N-伊拉锐', 'N-朱诺',
    'C-弗蕾娅', 'C-艾什', 'C-半藏', 'C-堡垒', 'C-法老之鹰', 'C-黑百合', 'C-黑影', 'C-回声', 'C-卡西迪', 'C-狂鼠', 'C-猎空', 'C-美', 'C-莫伊拉', 'C-士兵76', 'C-死神',
    'C-索杰恩', 'C-探奇', 'C-托比昂', 'C-源氏', 'C-秩序之光',
    'T-奥丽莎', 'T-查莉娅', 'T-D.VA', 'T-骇灾', 'T-拉玛刹', 'T-莱因哈特', 'T-路霸', 'T-毛加', 'T-末日铁拳', 'T-破坏球', 'T-温斯顿', 'T-西格玛', 'T-渣客女王'
];

window.PRESET_PLAYERS = [
    {name: '狗哥', level: 4, preferredRole: 'any'},
    {name: '小宇', level: 4, preferredRole: 'any'},
    {name: '孙妈', level: 4, preferredRole: 'any'},
    {name: '怪物', level: 4, preferredRole: 'any'},
    {name: '叫我泽村就行啦', level: 4, preferredRole: 'any'},
    {name: '牢fu', level: 4, preferredRole: 'any'},
    {name: 'lianhua', level: 4, preferredRole: 'any'},
    {name: '礼貌哥', level: 4, preferredRole: 'any'},
    {name: '婆娑月', level: 4, preferredRole: 'any'},
    {name: '口水哩啦子', level: 4, preferredRole: 'any'},
    {name: '腦內放映', level: 4, preferredRole: 'any'},
    {name: '小阳', level: 4, preferredRole: 'any'},
    {name: '🍆', level: 3, preferredRole: 'any'},
    {name: '内鬼', level: 3, preferredRole: 'any'},
    {name: 'Evenstar', level: 3, preferredRole: 'any'},
    {name: 'xiao99', level: 3, preferredRole: 'any'},
    {name: '夏目蓝', level: 3, preferredRole: 'any'},
    {name: '别再打了啦', level: 3, preferredRole: 'any'},
    {name: '蓝喵', level: 3, preferredRole: 'any'},
    {name: '白', level: 3, preferredRole: 'any'},
    {name: 'RickyTT', level: 2, preferredRole: 'any'},
    {name: '嗡嗡叫', level: 2, preferredRole: 'any'},
    {name: '小岳', level: 2, preferredRole: 'any'},
    {name: 'vison', level: 2, preferredRole: 'any'},
    {name: '八级大狂风', level: 2, preferredRole: 'any'},
    {name: '吼爹', level: 2, preferredRole: 'any'},
    {name: '帕帕尔', level: 2, preferredRole: 'any'},
    {name: '卖糖的麦兜', level: 2, preferredRole: 'any'},
    {name: '小怡', level: 2, preferredRole: 'any'},
    {name: '七崽', level: 2, preferredRole: 'any'},
    {name: '巴蒂', level: 2, preferredRole: 'any'},
    {name: '附子', level: 2, preferredRole: 'any'},
    {name: '糕耀太', level: 2, preferredRole: 'any'},
    {name: '小匕首', level: 1, preferredRole: 'any'},
    {name: '齐格勒', level: 1, preferredRole: 'any'},
    {name: '夏风', level: 1, preferredRole: 'any'},
    {name: '包饭', level: 1, preferredRole: 'any'},
    {name: '慢树', level: 1, preferredRole: 'any'},
    {name: '娜姐', level: 1, preferredRole: 'any'},
    {name: '一个人睡着', level: 1, preferredRole: 'any'},
    {name: '明天还会再见吗', level: 1, preferredRole: 'any'},
    {name: '爆炸无敌小恐龙', level: 1, preferredRole: 'any'},
    {name: '嗡嗡叫', level: 1, preferredRole: 'any'},
    {name: '马丘比丘的小羊', level: 1, preferredRole: 'any'},
    {name: '迷迷', level: 1, preferredRole: 'any'},
    {name: '璃璃宝贝', level: 1, preferredRole: 'any'},
    {name: 'SuperLu', level: 1, preferredRole: 'any'},
    {name: 'laso', level: 1, preferredRole: 'any'},
    {name: 'ONENONLY', level: 1, preferredRole: 'any'},
    {name: 'Hakunamtata', level: 1, preferredRole: 'any'},
    {name: '傲娇姬', level: 1, preferredRole: 'any'},
    {name: '豪门', level: 1, preferredRole: 'any'},
    {name: '十年', level: 1, preferredRole: 'any'},
    {name: '拔刀能留住落樱么', level: 1, preferredRole: 'any'},
    {name: 'Meditatg', level: 1, preferredRole: 'any'},
    {name: 'PeanutFan', level: 1, preferredRole: 'any'},
    {name: 'SuperSix', level: 1, preferredRole: 'any'},
    {name: 'TAEYEON', level: 1, preferredRole: 'any'},
    {name: 'Yuki', level: 1, preferredRole: 'any'},
    {name: 'hao', level: 1, preferredRole: 'any'},
    {name: '花落微凉梦清幽', level: 1, preferredRole: 'any'},
    {name: '可以亲亲猫猫头吗', level: 1, preferredRole: 'any'},
    {name: '摸头杀', level: 1, preferredRole: 'any'},
    {name: '如果当时', level: 1, preferredRole: 'any'},
    {name: '伤心猫猫', level: 1, preferredRole: 'any'},
    {name: '她说你给不起', level: 1, preferredRole: 'any'},
    {name: '在逃胖熊猫', level: 1, preferredRole: 'any'},
    {name: '驴驴', level: 1, preferredRole: 'any'},
    {name: '万里马', level: 1, preferredRole: 'any'},
    {name: '迈克米伦庄园园长', level: 1, preferredRole: 'any'},
    {name: 'kokumeow', level: 1, preferredRole: 'any'},
];
