window.PRESET_PLAYERS = [
    {name: ' 小 99', level: 3, preferredRole: 'any', description: '将军'},
    {name: ' 白丶 ', level: 2, preferredRole: 'any', description: '圣母——永远相信能感化所有人'},
    {name: ' 嗡嗡叫 ', level: 2, preferredRole: 'any', description: '男人们的加油站，啊~'},
    {name: ' 弥冬菌 ', level: 1, preferredRole: 'any', description: '詹姆斯邦娜'},
    {name: 'Ricky', level: 3, preferredRole: 'any', description: '没什么描述的，就是一条忠诚的🐕'},
    {name: ' 小宇 ', level: 4, preferredRole: 'any', description: '官方指定起飞人员，架起来就停不下'},
    {name: ' 手撕包饭 ', level: 1, preferredRole: 'any', description: '群一什 + 群一小炮台 + 燃起来的摩西'},
    {name: ' 孙妈妈 ', level: 4, preferredRole: 'any', description: '炸鱼的头子，宗师专炸下三段'},
    {name: ' 没有名字的怪物 ', level: 4, preferredRole: 'any', description: '内战高喊求内幕的老怪物'},
    {name: ' 明天还会再见吗 ', level: 1, preferredRole: 'any', description: '🐉神的老婆，是否唯一未知'},
    {name: 'fufu', level: 4, preferredRole: 'any', description: '走位风骚，人比走位还骚'},
    {name: 'laso', level: 1, preferredRole: 'any', description: '不涉黄不水群，闻着骚味自己就来了'},
    {name: ' 内鬼 ', level: 4, preferredRole: 'any', description: '无能的内鬼'},
    {name: ' 狗哥 ', level: 4, preferredRole: 'any', description: '宗师枪法，青铜站位'},
    {name: 'ONENONLY', level: 1, preferredRole: 'any', description: '小炮台2号'},
    {name: 'Vision', level: 2, preferredRole: 'any', description: '永远都是主播模式的靓仔'},
    {name: ' 茄子 ', level: 3, preferredRole: 'any', description: '蔬菜，又能输又菜'},
    {name: ' 夏目蓝 ', level: 3, preferredRole: 'any', description: '蛆王，能在团战里原地蛀穿盾牌'},
    {name: ' 小匕首 ', level: 2, preferredRole: 'any', description: '匕姆斯邦德，6帧的超级大蛆'},
    {name: ' 奶酪姐 ', level: 1, preferredRole: 'any', description: '奶酪哥的老婆，随时可以奶酪哥附体'},
    {name: ' 小怡 ', level: 2, preferredRole: 'any', description: '小手指发起人，点点点'},
    {name: ' 小岳 ', level: 1, preferredRole: 'any', description: '辛苦的打工仔'},
    {name: ' 一个人睡着 ', level: 2, preferredRole: 'any', description: '蛆，小99的跟班'},
    {name: ' 崽崽 ', level: 2, preferredRole: 'any', description: '法官型玩家，判你死刑只需一个大招'},
    {name: ' 爆炸无敌小恐龙 ', level: 2, preferredRole: 'any', description: '🐉神，身后永远跟着一群追随者'},
    {name: ' 奶酪哥 ', level: 4, preferredRole: 'any', description: '奶酪姐的老公，他太想赢了！！！'},
    {name: ' 别再打了啦 ', level: 3, preferredRole: 'any', description: '内战number one'},
    {name: ' 摸头杀 ', level: 2, preferredRole: 'any', description: '白姐父Dota的小迷弟'},
    {name: 'lianhua', level: 4, preferredRole: 'any', description: '无妹不o，曾对linbo痴狂'},
    {name: 'Evenstar', level: 3, preferredRole: 'any', description: '冷静男律，对游戏有法律级理解'},
    {name: ' 培根芝士牛肉蛋堡 ', level: 2, preferredRole: 'any', description: '疯狂大级？'},
    {name: ' 婆娑月 ', level: 4, preferredRole: 'any', description: '英杰月帝'},
    {name: ' 拔刀能留住落樱么 ', level: 1, preferredRole: 'any', description: '2025年的18岁男高弟弟'},
    {name: ' 帕帕尔 ', level: 2, preferredRole: 'any', description: '永远被老怪物放在敌对阵营'},
    {name: ' 齐格勒医生 ', level: 2, preferredRole: 'any', description: '真正意义上的战地医生'},
    {name: ' 在爱就不礼貌了 ', level: 4, preferredRole: 'any', description: '本人很礼貌但单挑绝不仁慈'},
    {name: ' 章鱼 ', level: 1, preferredRole: 'any', description: '喜欢自我欺骗的数字人'},
    {name: ' 四月绽放桜花雨 ', level: 3, preferredRole: 'any', description: '听说是百强蛆'},
    {name: 'SuperLu', level: 3, preferredRole: 'any', description: '性感露背男'},
    {name: ' 吼爹 ', level: 3, preferredRole: 'any', description: '渣克镇的话事人'},
    {name: ' 叫我泽村就行啦 ', level: 4, preferredRole: 'any', description: '芙蕾雅专精'},
    {name: ' 巴蒂 ', level: 2, preferredRole: 'any', description: '二次元铁拳'},
    {name: ' 慢树 ', level: 1, preferredRole: 'any', description: '关键时刻稳得离谱'},
    {name: ' 腦內放映 ', level: 3, preferredRole: 'any', description: '未知'},
    {name: ' 傲娇 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 扮猪吃饲料 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: 'kokumeow', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 口水哩啦子 ', level: 4, preferredRole: 'any', description: '未知'},
    {name: ' 璃璃 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 凌翊 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 驴驴 ', level: 3, preferredRole: 'any', description: '未知'},
    {name: 'PeanutFan', level: 3, preferredRole: 'any', description: '未知'},
    {name: '软软', level: 3, preferredRole: 'any', description: '孙妈的启蒙艺术老师'},
    {name: '喵喵大魔王', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 迈克米伦庄园园长 ', level: 4, preferredRole: 'any', description: '未知'},
    {name: ' 马丘比丘的小羊 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 星野哲 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 章鱼 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 迷迷 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: 'ELMTREEYMY', level: 3, preferredRole: 'any', description: '未知'},
    {name: ' 附子 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 十年生死两茫茫 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 是你的小祖宗 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 糕耀太 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: 'hao', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 豪门将进酒 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: 'SuperSix', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 他说逗逗就好了 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 她说你给不起 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 万里马 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 无聊的鲁肃 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 夏风归阙 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 小阳 ', level: 4, preferredRole: 'any', description: '未知'},
    {name: ' ohman ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 花落微涼夢清幽 ', level: 2, preferredRole: 'any', description: '未知'},
    {name: ' 可以亲亲猫猫头吗 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 伤心猫猫 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' Meditatg ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' Yuki ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 在逃胖熊猫 ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' TAEYEON ', level: 1, preferredRole: 'any', description: '未知'},
    {name: ' 如果当时 ', level: 1, preferredRole: 'any', description: '未知'},
];
window.DEFAULT_HERO_POOL = [
    'N-无漾', 'N-安娜', 'N-巴蒂斯特', 'N-布丽吉塔', 'N-禅雅塔', 'N-卢西奥', 'N-生命之梭', 'N-天使', 'N-雾子', 'N-伊拉锐', 'N-朱诺', 'N-莫伊拉',
    'C-弗蕾娅', 'C-艾什', 'C-半藏', 'C-堡垒', 'C-法老之鹰', 'C-黑百合', 'C-黑影', 'C-回声', 'C-卡西迪', 'C-狂鼠', 'C-猎空', 'C-美', 'C-士兵76', 'C-死神',
    'C-索杰恩', 'C-探奇', 'C-托比昂', 'C-源氏', 'C-秩序之光',
    'T-奥丽莎', 'T-查莉娅', 'T-D.VA', 'T-骇灾', 'T-拉玛刹', 'T-莱因哈特', 'T-路霸', 'T-毛加', 'T-末日铁拳', 'T-破坏球', 'T-温斯顿', 'T-西格玛', 'T-渣客女王'
];
window.MAP = [
    '伊利奥斯',
    '漓江塔',
    '尼泊尔',
    '绿洲城',
    '釜山',
    '斗兽场',
    '埃斯佩兰萨',
    '新皇后街',
    '多拉多',
    '66号公路',
    '直布罗陀',
    '渣客镇',
    '里阿尔托',
    '哈瓦那',
    '好莱坞',
    '国王大道',
    '努巴尼',
    '艾兴瓦尔德',
    '暴雪世界'
]